#national_structure.ini
[_ARCHIVE]

[_ADMIN]
_WRITTING = 
_WRLDBLD =
_CHARACTER =
_PLOTOUTLINES =
_SCRIPTS =
_OTHER =
_WELCOME =
_LEGAL =
[_ANIM]
_TCB =
	Season-01(S-01),
	Season-02(S-02),
	Season-03(S-03),
_BP =
	Episodes-1-50(EP001-050),
	Episodes-50-100(EP051-100),
[_GAME]
_PLT =
	Platformer-Test(Test-01),

[_AssetLibrary]