#project_folder_structure_blockParody.ini
[00_Dalies]

[01_Deliverables]

[02_Links]
Plugins=LINK:U:\PBK\SanAntonio\Design\04_AssetsPluginsTemplates

[03_Reference]
0301_Video=
0302_PureRef=
0303_Script=

[04_Assets-Components]

[05_Project]
0501_ProjectFiles=
	Blender,
	Substance,
	Photoshop,
0502_PostProcess=
	PP,
	Logos,
	Audio,

[06_PR]
