#folder_structure_asset_library.ini
[_Materials]
_Glass =
_Metal =
_Concrete =
_Wood =
_Stones =
_Brick =
_Ground =
_Plastic =
_WallCoverings =
_RoofCoverings =
_Ceilings =
_Grids =
_MarbleAndGranite =
_Tiles =
_Fabric =
_Leather =
_InteriorMapping =
_CarPaint =
_Tire =
_Facades =

[_Vegetation]
_Coastal = 
	_Trees,
	_Bushes,
	_GrassesAndFlowers,
	_Rocks,
	_Misc,
_Central = 
	_Trees,
	_Bushes,
	_GrassesAndFlowers,
	_Rocks,
	_Misc,
_Desert =
	_Trees,
	_Bushes,
	_GrassesAndFlowers,
	_Rocks,
	_Misc,
_PacificNothwest =
	_Trees,
	_Bushes,
	_GrassesAndFlowers,
	_Rocks,
	_Misc,

[_Objects]
_Sports = 
	Basketball(_Basketball),
	Football(_Football),
	Soccer(_Soccer),
	VolleyBall(_VolleyBall),
	Tennis(_Tennis),
_College =
_HighSchool =
_MiddleSchool =
_ElementarySchool =
_SpecialtyEquiptment = 
	_Woodshop,
	_Welding,
	_Automotive,
	_Robotics,
	_Nursing,
	_Engineering,
	_Makerspace,
_Entertaiment =
_Retail =
_Library =
_ClutterObjects =
_CityAndCampus =
_Background =

[_Lights-IES] 

[_HDRI]
_Skies =
_Indoor =
_Outdoor =
_Studio =

[_Megascans]

[_AdobieSubstance]

[_Tools]

[_Vehicles]
_Cars =
_Trucks =
_Buses =
_Electric =
_Other =

[_Characters2D]
_Sports = 
	Basketball(_Basketball),
	Football(_Football),
	Soccer(_Soccer),
	VolleyBall(_VolleyBall),
	Tennis(_Tennis),
_College =
_HighSchool =
_MiddleSchool =
_ElementarySchool =
_SpecialtyPrograms = 
	_Woodshop,
	_Welding,
	_Automotive,
	_Robotics,
	_Nursing,
	_Engineering,
	_Makerspace,
_Entertaiment =
_Retail =

[_Characters3D]
_Sports = 
	Basketball(_Basketball),
	Football(_Football),
	Soccer(_Soccer),
	VolleyBall(_VolleyBall),
	Tennis(_Tennis),
_College =
_HighSchool =
_MiddleSchool =
_ElementarySchool =
_SpecialtyPrograms = 
	_Woodshop,
	_Welding,
	_Automotive,
	_Robotics,
	_Nursing,
	_Engineering,
	_Makerspace,
_Entertaiment =
_Retail =

[_CharactersAnimated]
_Sports = 
	Basketball(_Basketball),
	Football(_Football),
	Soccer(_Soccer),
	VolleyBall(_VolleyBall),
	Tennis(_Tennis),
_College =
_HighSchool =
_MiddleSchool =
_ElementarySchool =
_SpecialtyPrograms = 
	_Woodshop,
	_Welding,
	_Automotive,
	_Robotics,
	_Nursing,
	_Engineering,
	_Makerspace,
_Entertaiment =
_Retail =