#national_structure.ini
[_ARCHIVE]

[_IT]

[_ADMIN]

[_BEAM]

[_ETHER]

[_LEAF]

[_PBK]
CA = 
	Anaheim(ANH),
	Bakersfield(BKF),
	Berkeley(BER),
	Folsom(FOL),
	Fresno(FRE),
	Los_Angeles(LAX),
	Rancho_Cucamonga(RCH),
	San_Diego(SDG),
	San_Luis_Obispo(SLO),
FL = 
	Coral_Gables(CGB),
	Fort_Myers(FMY),
	Jacksonville(JAX),
	Orlando(ORL),
	Sarasota(SRQ),
	St._Petersburg(STP),
	Tampa(TPA),
	West_Palm_Beach(WPB),
GA = 
	Griffin(GRF),
	Sugar_Hill(SGH),
MD = 
	Baltimore(BAL),
SC = 
	Greenville(GVL),
	Rock_Hill(RKH),
TX = 
	Austin(AUS),
	Dallas(DAL),
	Denton(DEN),
	Fort_Bend(FBN),
	Fort_Worth(FWT),
	Houston(HOU),
	Katy(KTY),
	San_Antonio(SAT),
	The_Woodlands(WDL),
VA = 
	Richmond(RIC),
WA = 
	Tacoma(TCM),

[_VIZLAB]
TX = 
	San_Antonio(SAT)

[_AssetLibrary]