#office_structure.ini
[_AssetLibrary]
Plugins=LINK:U:\PBK\SanAntonio\Design\04_AssetsPluginsTemplates

[_ResearchProjects]

[_ArchitectureProjects]
_ProspectiveProjects =
_ActiveProjects =
_ArchiveProjects = 
	15,
	19,
	20,
	21,
	22,
	23,
	24,
	25,
[_MarketingProjects]

[_Admin]
