#project_folder_structure_viz.ini
[00_Progress]

[01_Deliverables]

[02_Links]
Plugins=LINK:U:\PBK\SanAntonio\Design\04_AssetsPluginsTemplates

[03_Reference]

[04_Project]
0401_ProjectFiles=
	Blender,
	Revit,
	Sketchup,
	Twinmotion,
0402_PostProcess=
	PP,
	Logos,
	Audio,

[05_3DPrint]
0501_Building&Site=
0502_Context=
0503_PrintReady=
0504_CompetedProjectImages=

[06_PR]
