#project_folder_structure_architecture.ini
[00_Progress]

[01_Deliverables]

[02_Links]
Plugins=LINK:U:\PBK\SanAntonio\Design\04_AssetsPluginsTemplates

[03_Reference-RecievedFiles]

[04_Assets-Components]

[05_ProjectFiles]
1-Contracts = 	
	1A-Owner-Arch_Agreemnet,
	1B-Arch-Consultant_Agreements,
	1C-Original_RFQ,
2-Production = 	
	2A-Schedule,
	2B-Program,
	2C-Cost_Estimates,
	2D-Owner_Standards,
	2E-Meetings,
	2F-Code_Analysis,
	2G-Drawings,
	2H-Project_Manual,
	2I-Deliverables,
	2J-QA_QC,
	2K-Addenda,
	2L-Permitting_Agencies,
	2M-Team_Management,
	2N-Correspondance,
3-Bid_Proposals = 
	3A-Pre_Proposal,
	3B-Proposal,
	3C-Letter_or_Recommendation,
	3D-Correspondence,
4-CA = 
	4A-Owner_GC_Agreement,
	4B-OAC_Meetings,
	4C-Color_Selections,
	4D-Submittals,
	4E-Supplemental_Drawings,
	4F-CPR_AEA_Change_Orders,
	4G-Pay_Applications,
	H-Observation_Reports_Job_Photos,
	4I-Test_Lab_Reports,
	4J-Current_Set,
	4k-Correspondance,
5-Close_Out = 
	5A-Close_Out_Log,
	5B-Project_Directory,
	5C-Close_Out_Documents_and_Affidavits,
	5D-Project_Documetns_and_Certificates,
	5E-Warranties_and_Hazardous_Materials,
	5F-Insurance,
	5G-Receipts,
	5H-Record_Documents,
	5I-11_Month_Walk,
	5J-Agency_Close_Out,
6-Marketing = 
	6A-Events,
	6B-Marketing_RFP,
	6C-Project_Info,
	6D-Project_Photos,
